import { signal } from '@preact/signals';
import { pairWithCode, createBoard, setControllerToken, resolveToken } from '../services';
import { initializeApp, STORAGE_KEY } from '../services/lifecycle';

const pairCode = signal('');
const isPairing = signal(false);
const pairError = signal<string | null>(null);
const useToken = signal(false);

async function handlePair() {
    isPairing.value = true;
    pairError.value = null;

    try {
        if (pairCode.value.length !== 6) return;
        const result = await pairWithCode(pairCode.value);

        if (result.success && result.board_id) {
            if (result.token) {
                setControllerToken(result.token);
            }
            localStorage.setItem(STORAGE_KEY, result.board_id);
            await initializeApp(result.board_id);
        } else {
            pairError.value = result.error || 'Invalid pair code';
        }
    } catch (err) {
        pairError.value = (err as Error).message || 'Connection failed';
    } finally {
        isPairing.value = false;
    }
}

async function handleCreateBoard() {
    isPairing.value = true;
    pairError.value = null;

    try {
        const result = await createBoard();

        if (result.id) {
            localStorage.setItem(STORAGE_KEY, result.id);
            await initializeApp(result.id);
        } else {
            pairError.value = 'Failed to create board';
        }
    } catch {
        pairError.value = 'Connection failed';
    } finally {
        isPairing.value = false;
    }
}

export function PairingView() {
    return (
        <div class="pairing-view" data-testid="pairing-view">
            <div class="pairing-content">
                <h1 class="pairing-title">Connect to HorseBoard</h1>

                {useToken.value ? (
                    <div class="pairing-section">
                        <h2 class="pairing-section-title">Use Controller Token</h2>
                        <p class="pairing-description">
                            Enter the token generated by the board owner
                        </p>
                        <input
                            type="text"
                            class="pairing-input"
                            data-testid="token-input"
                            placeholder="hb_..."
                            value={pairCode.value}
                            onInput={(e) => {
                                pairCode.value = (e.target as HTMLInputElement).value;
                            }}
                        />
                        <button
                            class="pairing-btn pairing-btn-primary"
                            data-testid="token-connect-btn"
                            disabled={!pairCode.value.startsWith('hb_') || isPairing.value}
                            onClick={async () => {
                                isPairing.value = true;
                                try {
                                    setControllerToken(pairCode.value);

                                    const { board_id } = await resolveToken();

                                    if (board_id) {
                                        localStorage.setItem(STORAGE_KEY, board_id);
                                        const success = await initializeApp(board_id);
                                        if (!success) {
                                            pairError.value = "Failed to connect to board";
                                        }
                                    }
                                } catch (err) {
                                    console.error('Token connection failed:', err);
                                    pairError.value = "Invalid token or connection failed";
                                    // Clear invalid token
                                    setControllerToken(null);
                                } finally {
                                    isPairing.value = false;
                                }
                            }}
                        >
                            {isPairing.value ? 'Connecting...' : 'Connect'}
                        </button>
                        <button
                            class="pairing-link-btn"
                            onClick={() => {
                                useToken.value = false;
                                pairCode.value = '';
                                pairError.value = null;
                            }}
                        >
                            Back to Pair Code
                        </button>
                    </div>
                ) : (
                    <div class="pairing-section">
                        <h2 class="pairing-section-title">Join Existing Board</h2>
                        <p class="pairing-description">
                            Enter the 6-digit code shown on your TV board
                        </p>
                        <input
                            type="text"
                            class="pairing-input"
                            data-testid="pair-code-input"
                            placeholder="000000"
                            maxLength={6}
                            value={pairCode.value}
                            onInput={(e) => {
                                pairCode.value = (e.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, 6);
                            }}
                        />
                        <button
                            class="pairing-btn pairing-btn-primary"
                            data-testid="pair-btn"
                            disabled={pairCode.value.length !== 6 || isPairing.value}
                            onClick={handlePair}
                        >
                            {isPairing.value ? 'Connecting...' : 'Connect'}
                        </button>
                        <button
                            class="pairing-link-btn"
                            onClick={() => {
                                useToken.value = true;
                                pairCode.value = '';
                                pairError.value = null;
                            }}
                        >
                            I have a token
                        </button>
                    </div>
                )}

                <div class="pairing-divider">or</div>

                <div class="pairing-section">
                    <h2 class="pairing-section-title">Create New Board</h2>
                    <p class="pairing-description">
                        Start fresh with a new feed board
                    </p>
                    <button
                        class="pairing-btn"
                        data-testid="create-board-btn"
                        disabled={isPairing.value}
                        onClick={handleCreateBoard}
                    >
                        {isPairing.value ? 'Creating...' : 'Create New Board'}
                    </button>
                </div>

                {pairError.value && (
                    <div class="pairing-error" data-testid="pair-error">
                        {pairError.value}
                    </div>
                )}
            </div>
        </div>
    );
}
