export { sseClient } from './sse';
export {
  bootstrap,
  pairWithCode,
  createBoard,
  claimBoard,
  createHorse,
  updateHorse,
  deleteHorse,
  createFeed,
  updateFeed,
  deleteFeed,
  updateTimeMode,
  updateBoard,
  createControllerToken,
  listControllerTokens,
  revokeControllerToken,
  setControllerToken,
  resolveToken,
  pollProvisioning,
  linkDevice,
  listDevices,
  revokeDeviceToken,
  ApiError,
} from './api';
export type { BootstrapData, PairResult, ControllerToken } from './api';
